feat(recovery): Store and load wallet credentials in metadata
blockchain/blockchain-wallet-v4-frontend pull request #2728
Opened 2020-10-14 14:24 UTC by matsjj

## Description (optional)
Going forward, with the first login, the wallet will store the credentials for login, as in, guid, password and sharedKey in metadata. As such, using the mnemonic it will be possible to login to an existing wallet, even when 2FA has been lost. Doing it this way will keep all information related to nabu and the custodial part of the wallet, as the user is literally logging into the very same wallet. Previously it would create a new wallet instead with the old mnemonic. 

## Testing Steps (optional)
Happy to write a few tests if someone gives me a pointer on what should be tested ideally. 

For manual testing, use an old wallet, go through mnemonic recovery and discover that the GUID has changed. Upon logging in with this build, going through the same steps you should discover that the GUID has remained the same

2020-10-26 03:13 UTC, chtaili77 approved these changes

2020-11-30 11:07 UTC, Supattr0712 commented
ากัสื

2020-11-30 11:07 UTC, Supattr0712 commented
ย้ดสา

2020-11-30 11:07 UTC, Supattr0712 commented
ดร่ิ

2020-11-30 17:17 UTC, Supattr0712 commented
Bfgkkcduhc

2020-11-30 17:17 UTC, Supattr0712 commented
Hdkgdjjv

2020-11-30 17:17 UTC, Supattr0712 commented
Uhchkvc

2020-11-30 17:17 UTC, Supattr0712 commented
Bxhjc

2020-11-30 17:18 UTC, Supattr0712 commented
Jdtjgc

2020-11-30 17:18 UTC, Supattr0712 commented
Nxhkcfh

2020-11-30 17:18 UTC, Supattr0712 commented
Bxhlvcv

2020-11-30 17:19 UTC, Supattr0712 commented
Gdhkfd

2020-11-30 17:19 UTC, Supattr0712 commented
Gdhkfd

2020-11-30 17:19 UTC, Supattr0712 commented
Nxhknvff

2020-11-30 17:19 UTC, Supattr0712 commented
Hcgkhx

2020-11-30 17:19 UTC, Supattr0712 commented
[]()

2020-11-30 17:20 UTC, Supattr0712 commented
[]()

2020-11-30 17:20 UTC, Supattr0712 commented
[]()

2020-11-30 17:20 UTC, Supattr0712 commented
[]()

2020-11-30 17:20 UTC, Supattr0712 commented
Hfghv

2020-11-30 17:20 UTC, Supattr0712 commented
Ncfhh

2020-11-30 17:21 UTC, Supattr0712 commented
Hdfhjx

2020-11-30 17:21 UTC, Supattr0712 commented
Hfgjkgd

2020-11-30 17:21 UTC, Supattr0712 commented
John fu jbv

2020-11-30 17:22 UTC, Supattr0712 commented
Hchjf

2020-11-30 17:23 UTC, Supattr0712 commented
Bfgjh

2020-11-30 17:24 UTC, Supattr0712 commented
Bcdthg

2020-11-30 17:24 UTC, Supattr0712 commented
Uffh

2020-11-30 17:24 UTC, Supattr0712 commented
High kg

2020-11-30 17:24 UTC, Supattr0712 commented
Hdgkff

2020-11-30 17:24 UTC, Supattr0712 commented
Jbufdu

2020-11-30 17:24 UTC, Supattr0712 commented
Jvjfjd

2020-11-30 17:24 UTC, Supattr0712 commented
Nbfyg

2020-11-30 17:24 UTC, Supattr0712 commented
Kfdyhf

2020-11-30 17:24 UTC, Supattr0712 commented
Jfdfg

2020-11-30 17:25 UTC, Supattr0712 commented
Jfdgj

2020-11-30 17:25 UTC, Supattr0712 commented
Jcdgj

2020-11-30 17:25 UTC, Supattr0712 commented
Jcdhj

2020-11-30 17:25 UTC, Supattr0712 commented
Hdfh

2020-11-30 17:25 UTC, Supattr0712 commented
Hfdg

2020-11-30 17:25 UTC, Supattr0712 commented
Hffkh

2020-11-30 17:25 UTC, Supattr0712 commented
Bdfjg

2020-11-30 17:25 UTC, Supattr0712 commented
'Dfh

2021-02-05 20:22 UTC, yichok requested changes

2021-02-05 20:22 UTC, yichok commented on packages/blockchain-wallet-v4-frontend/src/assets/locales/es.json
>    "wallettour.airdrop.tooltip.stx": "Nuestro último airdrop con Blockstack ya está aquí. Asegúrese de conseguir sus Stacks (STX) gratis hoy.",
packages/blockchain-wallet-v4-frontend/src/assets/locales/es.json

2021-02-05 20:22 UTC, yichok commented
> ## Description (optional)
> Going forward, with the first login, the wallet will store the credentials for login, as in, guid, password and sharedKey in metadata. As such, using the mnemonic it will be possible to login to an existing wallet, even when 2FA has been lost. Doing it this way will keep all information related to nabu and the custodial part of the wallet, as the user is literally logging into the very same wallet. Previously it would create a new wallet instead with the old mnemonic.
> 
> ## Testing Steps (optional)
> Happy to write a few tests if someone gives me a pointer on what should be tested ideally.
> 
> For manual testing, use an old wallet, go through mnemonic recovery and discover that the GUID has changed. Upon logging in with this build, going through the same steps you should discover that the GUID has remained the same

2021-02-05 20:23 UTC, yichok approved these changes

2021-02-05 22:24 UTC, yichok approved these changes

2021-02-16 15:19 UTC, mpfluger commented on packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/actionTypes.js
> +export const SET_TRANSACTION_NOTE_WALLET_CREDENTIALS = '@CORE.SET_TRANSACTION_NOTE_WALLET_CREDENTIALS'
copy-pasta error?

2021-02-16 15:24 UTC, mpfluger commented on packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/sagas.js
> +  const createWalletCredentials = function * (kv) {
Maybe rename, `updateWalletCredentialsIfChangedOrMissing`

2021-02-16 15:25 UTC, mpfluger commented on packages/blockchain-wallet-v4/src/redux/kvStore/walletCredentials/sagas.js
> +      console.error(e)
Maybe not log the whole error

2021-02-19 23:12 UTC, schnogz approved these changes

2021-02-19 23:12 UTC, merged