feat(withdrawal lock): implemented dynamic load of lock interval
blockchain/blockchain-wallet-v4-frontend pull request #2767
Opened 2020-11-15 22:54 UTC by milan-bc

## Description (optional)
this PR replace all static usage of `3 days` and add dynamic way of showing `n days` where n is something we obtain from API

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2020-11-18 12:37 UTC, amadeo-bc commented
@plondon do you think you could review this today? BE is ready to release a change that might break the FE and it'd be great to get this into prod. 

https://blockc.slack.com/archives/G01EH5KSYEP/p1605088641000100

2020-11-19 17:25 UTC, schnogz requested changes

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts
> +            )).getOrFail({})
`getOrElse()` // fallback to 3 days

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
> +            )).getOrFail({})
make generic util saga in `packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.ts`

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
> +            )).getOrFail({})
call for all coins

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
> -            props.order.paymentType === 'USER_CARD' ? (
leave in `USER_CARD` check

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
> +                defaultMessage="In the meantime, you can sell into Cash, swap, and trade within Blockchain.com.<a href='https://support.blockchain.com/hc/en-us/articles/360048200392' rel='noopener no
remove `<a>` from text and add new formatttedMessage

2020-11-19 17:25 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/LockTimeTooltip/index.tsx
> +      Failure: () => null,
```
val => (
        <LockTime
          {...rest}
          lockTime={3}
        />
      ),
```

2020-11-19 20:56 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
> +            yield call(showWithdrawalLockAlert)
👏

2020-11-19 20:56 UTC, schnogz approved these changes

2020-11-19 20:56 UTC, merged