Removed text and functionality related to "What's New" flyover
blockchain/blockchain-wallet-v4-frontend pull request #2776
Opened 2020-11-17 21:40 UTC by blockdylanb

## Description (optional)
Removes the "What's New" link from the gear settings dropdown, as well as removes the associated flyover, and other code related to what's new functionality.

## Testing Steps (optional)
- Login, click the gear in the upper right corner, see that "What's New" is now gone.
- Make sure the rest of the application is working normally.

2020-11-17 21:53 UTC, TheLeoB approved these changes

2020-11-18 11:13 UTC, milan-bc approved these changes
LGTM great clean up @blockdylanb

2020-11-19 15:21 UTC, plondon commented on packages/blockchain-wallet-v4/src/redux/kvStore/config.js
> -  [WHATSNEW]: 2,
Makes sense

2020-11-19 15:24 UTC, schnogz requested changes
see comments above, lets leave those files alone and just add deprecated comments

2020-11-19 16:40 UTC, schnogz approved these changes

2020-11-19 16:42 UTC, merged