Fix/ach max buy
blockchain/blockchain-wallet-v4-frontend pull request #2869
Opened 2021-01-19 17:51 UTC by blockdylanb

## Description (optional)
Design changes to make arrow icons bigger on simple buy flow, remove the "x" from the top right, change FIAT/Crypto toggle icon, and make max buy/sell button not display actual ammounts

## Testing Steps (optional)
Open simple buy flow and it should look more like this: 
![image](https://user-images.githubusercontent.com/57680122/105073080-6e98a580-5a3b-11eb-9f1c-d39b8d843ea6.png)

2021-01-19 18:01 UTC, blockdylanb commented on packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/index.tsx
> +  transform: rotate(180deg);
I tried all the different "right" arrows we had, but none of them were the larger skinnier ones so I just used the "arrow-back" icon and rotated it to get the desired style.

2021-01-19 22:55 UTC, schnogz requested changes

2021-01-19 22:55 UTC, schnogz commented on package.json
> +  "version": "4.47.13",
undo

2021-01-19 23:57 UTC, blockdylanb commented on package.json
> +  "version": "4.47.13",
done

2021-01-20 00:46 UTC, schnogz approved these changes

2021-01-20 00:46 UTC, merged