chore(borrow): removing all borrow features/pages/components
blockchain/blockchain-wallet-v4-frontend pull request #2931
Opened 2021-02-18 15:55 UTC by pedroapfilho

Basically deleted all the components/pages from the `Borrow` feature.

2021-02-19 19:31 UTC, Toronto00 approved these changes

2021-02-19 19:31 UTC, Toronto00 requested changes
- [ ]

2021-03-02 01:08 UTC, schnogz approved these changes

2021-03-04 14:36 UTC, plondon commented
Nice

2021-07-14 17:45 UTC, merged