Feat/sso unified signin
blockchain/blockchain-wallet-v4-frontend pull request #3829
Opened 2021-11-08 15:45 UTC by TheLeoB

## Description (optional)
Add a concise explanation of the changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2021-12-09 18:03 UTC, schnogz requested changes

2021-12-09 18:03 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/selectors.ts
> +import { LOGIN_FORM_NAME } from './model'
can we use the constant from `data` so we dont have this in two places? i.e. i think its `data.auth.model.LOGIN_FORM`

2021-12-09 18:03 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx
>  export const LOGIN_FORM_NAME = 'login'
made a comment below about this, but lets remove this and use the one in data.auth.model

2021-12-09 18:03 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx
>  export const LOGIN_FORM_NAME = 'login'
you could actually just import from data here and then re-export for this model file so you dont have to track down all the other spots and update

2021-12-09 18:05 UTC, schnogz requested changes

2021-12-09 18:05 UTC, schnogz commented on package.json
> +    "base64url": "^3.0.1",
remove the `^` and then re-run yarn to get new lockfile

2021-12-09 22:50 UTC, TheLeoB commented on packages/blockchain-wallet-v4-frontend/src/data/balance/sagas.js
> +
Oof, I don't know. Probably merge conflict mistake will fix.

2021-12-10 20:17 UTC, schnogz requested changes

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/todoList.md
> +3. Login/AccountUnification/UpgradeSuccess probably only needs one template
can probably delete this file

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/TwoFA/index.tsx
> +          <WalletNeedHelpLink authActions={props.authActions} origin='PASSWORD' />
should origin be `2FA`?

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/TwoFA/index.tsx
> +          <ExchangeNeedHelpLink authActions={authActions} origin='IDENTIFIER' />
is origin correct?

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/AccountUnification/UpgradePassword/index.tsx
> +        {/* <NeedHelpLink authActions={props.authActions} origin='UPGRADE_ACCOUNT_NEW_PASSWORD' /> */}
are these commented out lines needed? if not, lets remove

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/Login/AccountUnification/ProductPicker/index.tsx
> +// min width
this needed? can we implement?

2021-12-10 20:17 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts
> +    // TODDO: WRAP ABOVE IN FEATURE FLAG
this needs to be done before merge?

2021-12-10 23:48 UTC, TheLeoB commented on packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
> +  'scenes.login.wallet.mobile_login.description.android': '<b>Android</b> - Tap the QR code icon at the top right corner of the app.'
I think the instructions are different for the different platforms. Could add an icon or an 'OR'. Will follow up about this with design.

2021-12-14 14:26 UTC, merged