feat(wallet): changing more labels from `wallet` to `account` wording
blockchain/blockchain-wallet-v4-frontend pull request #4155
Opened 2022-02-03 19:29 UTC by cmonti-bc

## Description (optional)
More labels that were found with `wallet` wording that should change into `account` wording.

2022-02-03 19:30 UTC, jtk-bc approved these changes

2022-02-03 19:32 UTC, gsas-bc commented on packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
> +export type DefaultMessageType = MessagesType[MessageIdType]
Missing new line?

2022-02-03 19:32 UTC, gsas-bc submitted a review, later dismissed

2022-02-03 19:33 UTC, cmonti-bc commented on packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
> +export type DefaultMessageType = MessagesType[MessageIdType]
Great catch, fixed.

2022-02-03 19:48 UTC, schnogz requested changes
I think these changes are too broad.  We still need to use the term Wallet in many of these contexts since they are using the Wallet product.   @amadeo-bc thoughts?

2022-03-15 12:55 UTC, amadeo-bc commented
Reopening. I need to look at this before we release unified signup.

2022-05-04 19:25 UTC, closed without merging