feat(kyc): prevent showing flow if user has been rejected
blockchain/blockchain-wallet-v4-frontend pull request #4162
Opened 2022-02-07 15:08 UTC by milan-bc

## Description (optional)
Add a concise explanation of the changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2022-02-07 16:14 UTC, schnogz requested changes

2022-02-07 16:14 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/index.tsx
> +          </Flyout>
can we move the `<FlyoutChild>` out of each switch case and a level higher? eg.
```
<Flyout>
  <FlyoutChild>
      {.... switch logic}
  </FlyoutChild>
</Flyout>
```

2022-02-07 16:21 UTC, blockdylanb approved these changes

2022-02-07 16:34 UTC, milan-bc commented on packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/index.tsx
> +import Rejected from '../../../components/Rejected'
@blockdylanb nah that one doesn't work :( we might add new alias

2022-02-08 13:07 UTC, schnogz approved these changes

2022-02-08 13:07 UTC, merged