feat(nfts): add in asset page init styling
blockchain/blockchain-wallet-v4-frontend pull request #4199
Opened 2022-02-11 22:00 UTC by rsteubs-bc

## Description (optional)
asset page init styling

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2022-02-15 20:17 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAsset.graphql
> +    date_ingested
We don't need all these fields, we should only request what we need

2022-02-18 13:11 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
> +      state.openSeaStatus = Remote.Loading
state.openseaAsset =

2022-02-18 13:12 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
> +      state.openSeaStatus = Remote.Failure(action.payload)
state.openseaAsset =

2022-02-18 13:14 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  color: #121d33;
import colors from constellation

color: ${colors.grey900}

2022-02-18 13:14 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  color: #121d33;
import colors from constellation

color: ${colors.grey900}

2022-02-18 13:14 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  background: #f0f2f7;
import colors from constellation

color: ${colors.XYZ}

2022-02-18 13:15 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  border: 1px solid #dfe3eb;
import colors from constellation

2022-02-18 13:16 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  const NULL_ADDRESS = '0x0000000000000000000000000000000000000000'
NULL_ADDRESS already defined in @core package somewhere. Import from there.

const WETH_ADDRESS = window.coins.WETH.type.erc20Address

2022-02-18 13:16 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +      token_id: asset.data?.asset?.token_id || '8520'
Hmm maybe lets fail and display a 404 type page?

2022-02-18 13:17 UTC, plondon commented on packages/blockchain-wallet-v4/src/network/api/nfts/index.ts
> +      url: `https://api.opensea.io/api/v1/`
If you merge in latest changes you should see `openseaUrl`

2022-02-18 13:18 UTC, plondon requested changes
Havent pulled it down too look at it but just went through the code and found some small issues:

1. copy/pasta error in slice
2. import colors from constellation
3. other small fixes

Lmk when I can look again and Ill pull down!

2022-02-21 00:27 UTC, Marek0491 approved these changes
https://github.com/blockchain/blockchain-wallet-v4-frontend/tree/feat/opensea-graphql

2022-02-22 13:19 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
> +      yield put(A.fetchNftOffersMadeLoading())
fetchOpenseaAssetLoading()

2022-02-22 13:21 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  const NULL_ADDRESS = '0x0000000000000000000000000000000000000000'
import NULL_ADDRESS from @core

2022-02-22 13:21 UTC, plondon commented on packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
> +  const NULL_ADDRESS = '0x0000000000000000000000000000000000000000'
import { NULL_ADDRESS } from '@core/redux/payment/nfts/utils'

2022-02-22 13:23 UTC, plondon approved these changes
A few more small things and then Ill merge!

2022-02-22 20:51 UTC, merged