feat(terms and conditions): fixed rendering
blockchain/blockchain-wallet-v4-frontend pull request #4305
Opened 2022-03-09 23:36 UTC by milan-bc

## Description (optional)
Add a concise explanation of the changes.

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2022-03-09 23:51 UTC, blockdylanb commented on packages/blockchain-wallet-v4-frontend/src/components/Flyout/TermsAndConditions/index.tsx
> +                dangerouslySetInnerHTML={{ __html: props.termsAndConditions.termsAndConditions }}
I know this data is coming from our own endpoint so there's minimal risk here but just to be safe think we should wrap this in DOM purify https://www.npmjs.com/package/dompurify

2022-03-10 00:14 UTC, blockdylanb approved these changes
.

2022-03-10 00:15 UTC, blockdylanb requested changes
we should implement DOM purify on the dangerous html section.

2022-03-10 14:20 UTC, milan-bc commented
Let's wait until we are sure about HTML vs markdown

2022-03-10 16:11 UTC, blockdylanb commented on packages/blockchain-wallet-v4-frontend/src/components/Flyout/TermsAndConditions/index.tsx
> +                  __html: DOMPurify.sanitize(props.termsAndConditions.termsAndConditions)
👏🏻

2022-03-10 16:11 UTC, blockdylanb approved these changes

2022-03-10 16:11 UTC, merged