fix: typo after login on /home tab
blockchain/blockchain-wallet-v4-frontend pull request #4549
Opened 2022-04-20 15:10 UTC by cmonti-bc

## Description (optional)

![FcFeVTsebe](https://user-images.githubusercontent.com/97299628/164263021-4fc9983e-a245-4c19-836a-23289abb969c.gif)

2022-04-20 15:34 UTC, schnogz requested changes
Lets just keep this simple because your solution does not work for all use cases (sometimes users dont go to the homepage after login). Just change `layouts/Wallet/index.tsx` to set the page title to `Blockchain.com Wallet`.

2022-04-20 16:03 UTC, cmonti-bc commented
> Lets just keep this simple because your solution does not work for all use cases (sometimes users dont go to the homepage after login). Just change `layouts/Wallet/index.tsx` to set the page title to `Blockchain.com Wallet`.

2022-04-20 16:03 UTC, closed without merging

2022-04-20 16:34 UTC, schnogz approved these changes

2022-04-23 08:46 UTC, devildp333 commented
ขอบคุณจากหัวใจ