fix(recovery): skip email verification if metadata recovery
blockchain/blockchain-wallet-v4-frontend pull request #4790
Opened 2022-05-17 19:40 UTC by TheLeoB

## Description (optional)
Fixes issue where there's no email address after metadata recovery, and user can't proceed to wallet after mnemonic recovery. 

https://www.loom.com/share/becd850128e640e1b80a27ad77ea6ba6

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2022-05-17 19:44 UTC, schnogz requested changes

2022-05-17 19:44 UTC, schnogz commented on packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/index.tsx
> +import { is } from 'ramda'
i dont see this being used

2022-05-17 20:28 UTC, schnogz approved these changes

2022-05-17 20:28 UTC, merged

2022-05-18 10:56 UTC, sorrells81 reviewed
Where's my lost crypto currency's