fix(silver revamp): allow users to do swap
blockchain/blockchain-wallet-v4-frontend pull request #4949
Opened 2022-06-07 09:17 UTC by milan-bc

## Description (optional)
Since users are not tier 2 we are about to allow them to do swap if maxOrdersLeft is null/not set

## Testing Steps (optional)
Detail the steps required for the reviewer(s) to verify and test these changes.

2022-06-08 18:43 UTC, julianromero-bc commented on packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
> +      if (!userSwapBuyMore) {
agree on using clearer variable names. Found several parts of the code with lack of this

2022-06-13 13:31 UTC, pedroapfilho requested changes

2022-06-13 13:31 UTC, pedroapfilho commented on packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
> +      const userSwapBuyMore = !products.swap?.maxOrdersLeft || products.swap?.maxOrdersLeft > 0
You don't need to change the name of the variable here

2022-06-15 13:50 UTC, milan-bc commented on packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
> +      if (!userSwapBuyMore) {
There are only two hard things in Computer Science: cache invalidation and naming things. :) 
Will change to something more obvious in general it should mean that user can swap more

2022-06-16 19:40 UTC, pedroapfilho approved these changes

2022-06-17 12:18 UTC, merged