fix(login-error-overlap): move error to bottom
blockchain/blockchain-wallet-v4-frontend pull request #4997
Opened 2022-06-16 17:55 UTC by jjBlockchain

## Description (optional)
* move error message to bottom of input to avoid overlap
<img width="545" alt="Screen Shot 2022-06-16 at 1 55 15 PM" src="https://user-images.githubusercontent.com/53186076/174135213-f62bd804-2c8a-45e4-96b0-303dea1995ce.png">

2022-06-21 07:40 UTC, pedroapfilho requested changes

2022-06-21 07:40 UTC, pedroapfilho commented on packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js
> +  ${({ errorBottom }) => errorBottom && `padding-top: 4px;`}
make it 8

2022-06-21 18:55 UTC, julianromero-bc submitted a review, later dismissed

2022-06-22 13:20 UTC, schnogz approved these changes

2022-06-22 13:20 UTC, merged